### ISSUE TITLE
希望能利用這裡的程式碼來處理判決

### ISSUE THREAD

**Issue by billy3321** [lisez/rejdoc#5]
@lisez 您好！我是司改會的雨蒼。

司改會日前於g0v申請了[判決書API](https://grants.g0v.tw/projects/58749ce08798fb001e73251c)的計畫，希望能透過製作判決的API，讓法界理解開放資料的重要，也讓大家能有更好的判決書可以閱讀。

我們發現您採用的License是BSD，想請問一下能否採用您的程式碼來處理判決書內文段行問題，並[在未來Open Source的Repository上](https://github.com/jrf-tw/sunshine.jrf.org.tw)標明採用您的程式碼？

謝謝！

**Comment by lisez** [comment]
你好，採用程式碼僅要遵造BSD授權即可，其實不太了解你的意思？

**Comment by billy3321** [comment]
@lisez 我知道應該遵循BSD授權即可，但禮貌上還是跟您打個招呼，感謝您製作這個程式！
